# Generated by Django 5.2.15 on 2026-06-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alternativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('pontos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternativa_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternativa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
