# Generated by Django 5.2.15 on 2026-06-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_respostaexercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('objetivo', models.IntegerField(default=10)),
                ('realizados', models.IntegerField(default=0)),
                ('acertos', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
