# Generated by Django 5.2.15 on 2026-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_metadiaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaexercicio',
            old_name='created_at',
            new_name='data',
        ),
        migrations.AddField(
            model_name='metadiaria',
            name='estudou',
            field=models.BooleanField(default=False),
        ),
    ]
