# Generated by Django 5.2.15 on 2026-07-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cronograma_cronogramaitem'),
        ('core', '0012_rename_created_at_respostaexercicio_data_and_more'),
    ]

    operations = [
    ]
