# Generated by Django 5.2.15 on 2026-08-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cronograma_usuario_kanbantarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaitem',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronogramaitem',
            name='status',
            field=models.CharField(choices=[('PARA_FAZER', 'Para Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PARA_FAZER', max_length=20),
        ),
    ]
