# Generated by Django 5.2.15 on 2026-08-18 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_conquista_alter_cronograma_usuario_usuarioconquista'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FAZER', 'Para Fazer'), ('ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='FAZER', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
