# Generated by Django 5.2.15 on 2026-08-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cronogramaitem_ordem_cronogramaitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='materia_favorita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_favoritos', to='core.materia'),
        ),
        migrations.AddField(
            model_name='user',
            name='melhor_horario',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('MADRUGADA', 'Madrugada')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_diaria_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('MELHORAR_NOTAS', 'Melhorar notas'), ('VESTIBULAR', 'Passar em vestibular'), ('APRENDER', 'Aprender algo novo'), ('CONSTANCIA', 'Manter constância')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tema_cor',
            field=models.CharField(choices=[('AZUL', 'Azul'), ('ROXO', 'Roxo'), ('VERDE', 'Verde'), ('LARANJA', 'Laranja'), ('ROSA', 'Rosa'), ('CIANO', 'Ciano')], default='AZUL', max_length=10),
        ),
    ]
