# Generated by Django 5.2.15 on 2026-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_bio_user_materia_favorita_user_melhor_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadiaria',
            name='atividades',
            field=models.JSONField(default={}),
        ),
    ]
